--- 
title: "Geospatial Analysis of Chronic Diseases"
author: "Vritansh Kamal (vk2501),  Ritvik Khandelwal (rk3213), Maria Pratyusha (mp4145)"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

Chronic diseases are conditions that last 1 year or more and require ongoing medical attention or limit activities of daily living or both. The most common chronic diseases especially in adults are heart disease, cancer, chronic lung disease, stroke, Alzheimer's disease, diabetes, epilepsy, tooth decay, and chronic kidney disease. This can be caused by risk behaviors like tobacco use and exposure to passive smoke, poor nutrition, physical inactivity and excessive alcohol use. Six in ten adults in the US have a chronic disease and four out of ten from that lot have more than two.[1]
 
Given the advance in the healthcare industry following the pandemic we’ve chosen to study chronic diseases in the USA over the last decade. The dataset we’re using is taken from CDC [2] which consists of a record of people suffering from chronic diseases since 2001. It also provides us useful indicators on the geographies of these chronic diseases therefore would help us to dive into the geospatial analysis of the same. 
 
The data on chronic diseases gives us insights on the evolution of a particular disease over the time and in different geographical localities. It also serves as a major indicator of the health of the community in a particular geolocation based on the extent of the spread of the disease. This is where we see the true potential in exploring the data for analysis and visualization to deduce any reasonable assumption about the same backed by scientific proof such as news articles, hospitalization records etc. This can help us to formulate better policies based on our analysis and help to advance healthcare by investing in the same. 