# Proposal

## Research topic

Although the data is readily available it is still not possible to infer insights and trends from this data by just looking at it. To make it useful and discernable for the public, we have decided to perform a thorough exploratory data analysis through interactive visualizations thus enabling us to infer valuable insights/information from the data available to us. 
The columns we are planning to use are 
YearStart (Year Start) / YearEnd (Year End) - Intend to merge these 2 columns to make a single column named “Year” as the values of YearStart and YearEnd is the same in every row
LocationAbbr (Location Abbreviation) - Short form abbreviations of the locations. Useful for neat plots
LocationDec (Location description) - full forms of Location Abbreviations column
Data Source - Source from which the particular data point is collected 
Topic
stratification Category1 -  consisting of race, ethnicity, overall categories 
Stratification1 - The respective values of stratification Category1 column is contained in this column 
GeoLocation: The geographic Location of the particular data point. Useful for Geospatial Analysis 


Insights that can be potentially inferred or questions that we can potentially answer through this analysis:

Q - Spread of topic based on the geospatial data and location. can be done for every year to understand which locations are susceptible or improving with respect to a particular topic in each year.

Q - Which gender is more prone to get affected by a specific topic? 

Q - How are the genders getting affected by a specific topic through the progression of time?

Q - patterns between year/time and topic (highest, lowest, etc).

Q - Pattern between race/ethnicity and topics.

Q - Patterns between race/ethnicity and geolocation and relating it to topic. 

Q - Are there countries where males/females getting affected more

Q - Countries which are dealing with the most number of topics. Can try to infer which countries are more suitable to live because of less number of topics that they are dealing with?


## Data availability
The data source we are leveraging is https://catalog.data.gov/dataset/u-s-chronic-disease-indicators-cdi. This dataset is provided and maintained by the Centers for Disease Control and Prevention’s (CDC)  division of population health. This dataset was first published on 21st Feb, 2021 and the last update was done on 24th March, 2022. It is a publicly available dataset and licensed (https://opendefinition.org/licenses/odc-odbl/)  

 CDC's Division of Population Health provides a cross-cutting set of 124 indicators that were developed by consensus and that allows states and territories and large metropolitan areas to uniformly define, collect, and report chronic disease data that are important to public health practice and available for states, territories and large metropolitan areas. In addition to providing access to state-specific indicator data, the CDI web site serves as a gateway to additional information and data resources.
To monitor diseases and risk factors over time and to plan and implement effective interventions, public health agencies need access to the most relevant, up-to-date, and uniformly defined chronic disease surveillance data at the state and county level. The chronic disease indicators (CDIs) are a set of surveillance indicators developed by consensus among CDC, the Council of State and Territorial Epidemiologists (CSTE), and the National Association of Chronic Disease Directors (NACDD) and are available on the Internet. The CDI website enables public health professionals and policymakers to retrieve uniformly defined state-level and selected metropolitan-level data for chronic diseases and risk factors that have a substantial impact on public health. These indicators are essential for surveillance, prioritization, and evaluation of public health interventions for chronic disease. Most, if not all, of the current indicators are available and reported on other websites, either by the data providers or by categorical chronic disease programs. However, the CDI website is the only integrated source for comprehensive access to a wide range of indicators for the surveillance of chronic diseases, conditions, and risk factors at the state level and for selected large metropolitan areas. CDI data are obtained from several primary surveillance data. 

The expansion of the CDI set necessitates the inclusion of new sources of data. Previously, the CDIs relied on data from nine primary sources: the Behavioral Risk Factor Surveillance System (BRFSS), state cancer registries, the American Community Survey (ACS), birth and death certificates data in the National Vital Statistics System (NVSS), the State Tobacco Activities Tracking and Evaluation System, the United States Renal Data System, and the Youth Risk Behavior Surveillance System. The revised CDIs retain the use of data from these sources, and additional data will be obtained from the Pregnancy Risk Assessment Monitoring System, the Alcohol Epidemiologic Data System, the Alcohol Policy Information System, alcohol policy legal research, the National Survey of Children’s Health, State Emergency Department Databases, State Inpatient Databases, the Centers for Medicare and Medicaid Services Chronic Condition Warehouse and the Medicare Current Beneficiary Survey, the U.S. Department of Agriculture, the CDC School Health Profiles, Achieving a State of Healthy Weight, Maternal Practices in Infant Nutrition and Care, the Breastfeeding Report Card, the Health Resources and Services Administration Uniform Data System, the National Immunization Survey, and the Water Fluoridation Reporting System. Many of these, such as BRFSS, use complex sampling designs and weights that must be taken into account. Additional details on these data sources are provided (Table 4) of this paper https://www.cdc.gov/mmwr/pdf/rr/rr6401.pdf
The data is in the form of a Comma Separated Values file so we have basically downloaded this file on our local machine and plan to import it locally by reading the csv in R. After that we will proceed to perform further analysis. 




